{{- if .Values.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "openshift-oauthclient-manager.namespaceName" . }}
  labels:
    {{- include "openshift-oauthclient-manager.labels" . | nindent 4 }}
{{- end }}
