---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openshift-oauthclient-manager.name" . }}
  namespace: {{ include "openshift-oauthclient-manager.namespaceName" . }}
  labels:
    {{- include "openshift-oauthclient-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
