---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openshift-oauthclient-manager.name" . }}
  namespace: {{ include "openshift-oauthclient-manager.namespaceName" . }}
  labels:
    {{- include "openshift-oauthclient-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openshift-oauthclient-manager.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "openshift-oauthclient-manager.serviceAccountName" . }}
  namespace: {{ include "openshift-oauthclient-manager.namespaceName" . }}
