{{- if and .Values.serviceAccount.create (not .Values.odo) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshift-oauthclient-manager.serviceAccountName" . }}
  namespace: {{ include "openshift-oauthclient-manager.namespaceName" . }}
  labels:
    {{- include "openshift-oauthclient-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
