---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oauthclientconfigs.rhpds.redhat.com
spec:
  group: rhpds.redhat.com
  scope: Cluster
  names:
    plural: oauthclientconfigs
    singular: oauthclientconfig
    kind: OAuthClientConfig
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          Configuration for OAuthClient management
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9\-]*[a-z0-9]$
          spec:
            description: >-
              Spec for OAuthClient management
            type: object
            required:
            - grantMethod
            - redirectURIs
            - secret
            properties:
              accessTokenInactivityTimeoutSeconds:
                type: integer
              accessTokenMaxAgeSeconds:
                type: integer
              additionalSecrets:
                type: array
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
              grantMethod:
                type: string
                enum:
                - auto
                - prompt
              redirectURIs:
                type: array
                items:
                  type: string
              respondWithChallenges:
                type: boolean
              scopeRestrictions:
                type: array
                items:
                  type: object
                  properties:
                    clusterRole:
                      type: object
                      properties:
                        allowEscalation:
                          type: boolean
                        namespaces:
                          type: array
                          items:
                            type: string
                        roleNames:
                          type: array
                          items:
                            type: string
                    literals:
                      type: array
                      items:
                        type: string
              secret:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
          status:
            type: object
            properties:
              diffBase:
                description: Kopf diffbase
                type: string
              kopf:
                description: Kopf status
                type: object
                x-kubernetes-preserve-unknown-fields: true
